# Generated by Django 5.2.5 on 2025-08-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="travello.destination",
            ),
            preserve_default=False,
        ),
    ]
