# Generated by Django 5.2.5 on 2025-08-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0002_trip_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
